<?xml version="1.0" encoding="utf-8"?><Database Name="XML_to_DATABASE" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=SHREEKESHM\MSSQLSERVER2012;Initial Catalog=XML_to_DATABASE;User ID=sa" SettingsObjectName="UserManagement.Properties.Settings" SettingsPropertyName="XML_to_DATABASEConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.User_data" Member="User_datas">
    <Type Name="User_data">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Function Name="dbo.spCreateUser" Method="spCreateUser">
    <Parameter Name="FirstName" Parameter="firstName" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="LastName" Parameter="lastName" Type="System.String" DbType="NVarChar(20)" />
    <ElementType Name="spCreateUserResult">
      <Column Name="" Member="Column1" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.spSelectUserID" Method="spSelectUserID">
    <Parameter Name="FirstName" Parameter="firstName" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="spSelectUserIDResult">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.spDeleteUser" Method="spDeleteUser">
    <Parameter Name="Id" Parameter="id" Type="System.Int64" DbType="BigInt" />
    <ElementType Name="spDeleteUserResult">
      <Column Name="" Member="Column1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.spUpdateUser" Method="spUpdateUser">
    <Parameter Name="Id" Parameter="id" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="FirstName" Parameter="firstName" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
</Database>